name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Python code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install black isort autoflake

      - name: Check code formatting with black
        run: |
          black --check .

      - name: Check import sorting with isort
        run: |
          isort --check .

      - name: Check for unused imports and variables with autoflake
        run: |
          autoflake --check --recursive --remove-all-unused-imports --remove-unused-variables .

  # test:
  #   name: Run Django tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.x

  #     - name: Install dependencies
  #       run: |
  #         pip install -r requirements.txt

  #     - name: Run Django tests
  #       run: |
  #         python manage.py test
